# CLOSE_COLUMN_NUMBER = 9
# TIMESTAMP_COLUMN_NUMBER = 3
DAYS_TO_OBSERVE = 5
DECIMAL_PLACES = 2
FINAL_FILENAME = "sangam"
DURATION_OF_DATA = 120
EMA_FOR_DAYS = {
    11: 0.3,
    9: 0.15,
    13: 0.07
}

ZERODHA_CONFIG = {
    "API_KEY": "",
    "ACCESS_TOKEN": ""
}

